# Install Mambaforge: https://github.com/conda-forge/miniforge/releases
name: worldstrat
channels:
  - pytorch
  - conda-forge
  - defaults
  
dependencies:
  - python==3.8
  # For dataset notebooks
  - geographiclib
  - tqdm
  - shapely
  - pyproj
  - pandas
  - swifter
  - requests
  - sentinelhub
  - folium
  - geopandas
  - plotnine==0.9.0
  - matplotlib==3.5.2


  # For training/inference
  - numpy
  - pytorch-lightning==1.9.0
  - torchvision=0.11.3
  - wandb
  - setuptools==59.5.0
  - natsort
  - rasterio
  - kornia==0.6.3
  - lightning-bolts
  - cudatoolkit
  - pip
  # Because conda package is old (0.10.0 vs. 0.10.1)
  - pip:
    - eo-learn
    - pytorch-msssim
    - global_land_mask